services:
  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    ports:
      - "5001:5001"
    volumes:
      - ./amazon_images:/amazon_images

  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./amazon_images:/amazon_images
