services:
  product_recommendation_app:
    build: .
    ports:
      - "5001:5001"
    volumes:
      - ./models:/app/models
      - ./templates:/app/templates
    command: >
      sh -c "python app.py"
